### ISSUE TITLE
Minor: Error when ordered product is out of stock

### ISSUE THREAD

**Issue by maksuturva** [maksuturva/prestashop_payment_module#1]
Tested: in PrestaShop 1.6.0.9:

When in PrestaShop admin the setting "Allow ordering of out-of-stock products" is set to "Yes" and a customer buys product which is out of stock,  the customer receives both an order confirmation and a vague error message. 
However, the order is accepted (as a backorder) and registered. 
![image](https://cloud.githubusercontent.com/assets/8221639/5395032/4ef5c7c6-814d-11e4-9b36-112025607dad.png)

**Comment by kryysler** [comment]
This happens because only the "payed" state is checked here: https://github.com/maksuturva/prestashop_payment_module/blob/master/maksuturva/maksuturva.php#L660

Also the "PS_OS_OUTOFSTOCK" (PS 1.4, 1.5) and "PS_OS_OUTOFSTOCK_PAID" (PS 1.6) states should return an "ok" status.

**Comment by kryysler** [comment]
Fixed in commit 1ed98c4

**Comment by kryysler** [comment]
fix included in 2.0.0 release
